name: Publish and release

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - release-triggered

# Setup npm trusted publishing
permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 24

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: "release"
        id: publish
        run: script/ci/release.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
