name: Publish and release

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - release-triggered

# Setup npm trusted publishing
permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 24

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'

      - name: "release"
        id: publish
        run: script/ci/release.sh
        env:
          GITHUB_TOKEN: ${{ github.token }}
